name: setup

inputs:
  turbo-cache:
    default: true

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: env
      shell: bash
      run: |
        echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV
        echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV

    - name: yarn cache
      uses: actions/cache@v4
      if: ${{ !startsWith(github.ref_name, 'dependabot') }}
      with:
        key: yarn-${{ hashFiles('yarn.lock') }}
        path: ${{ env.YARN_CACHE_DIR }}

    - name: yarn cache ro
      uses: actions/cache/restore@v4
      if: ${{ startsWith(github.ref_name, 'dependabot') }}
      with:
        key: yarn-${{ hashFiles('yarn.lock') }}
        path: ${{ env.YARN_CACHE_DIR }}

    - name: turbo cache
      uses: actions/cache@v4
      if: ${{ inputs.turbo-cache && !startsWith(github.ref_name, 'dependabot') }}
      with:
        path: .turbo
        key: turbo-${{ github.sha }}
        restore-keys: |
          turbo-

    - name: turbo cache ro
      uses: actions/cache/restore@v4
      if: ${{ inputs.turbo-cache && startsWith(github.ref_name, 'dependabot') }}
      with:
        path: .turbo
        key: turbo-${{ github.sha }}
        restore-keys: |
          turbo-

    - name: install
      shell: bash
      run: yarn install
