name: deploy-e2e-report

inputs:
  netlify-auth-token:
    required: true
  netlify-site-id:
    required: true

runs:
  using: composite

  steps:
    - name: start deploy
      uses: bobheadxi/deployments@v1
      id: deployment
      with:
        step: start
        env: cypress

    - name: deploy
      id: netlify
      shell: bash
      run: node ./build/deploy-netlify.mjs --rootFolder=cypress/reports/html --exclude=.jsons --branch=${{ github.ref_name }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.netlify-auth-token }}
        NETLIFY_SITE_ID: ${{ inputs.netlify-site-id }}

    - name: finish deploy
      uses: bobheadxi/deployments@v1
      with:
        step: finish
        status: success
        env: ${{ steps.deployment.outputs.env }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        env_url: ${{ steps.netlify.url.deploy_url }}
