name: build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'examples/**'
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/workflows/shared/setup

      - name: build
        run: yarn ci:build

      - uses: dorny/test-reporter@1a288b62f8b75c0f433cbfdbc2e4800fbae50bd7
        if: ${{ (success() || failure()) && github.repository == 'mistic100/Photo-Sphere-Viewer' }}
        with:
          name: mocha
          use-actions-summary: true
          path: 'packages/*/reports/mocha.json'
          reporter: mocha-json

  e2e:
    if: ${{ !startsWith(github.ref_name, 'dependabot') }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/workflows/shared/setup

      - name: e2e
        run: |
          yarn ci:build
          yarn ci:e2e

      - uses: dorny/test-reporter@1a288b62f8b75c0f433cbfdbc2e4800fbae50bd7
        if: ${{ (success() || failure()) && github.repository == 'mistic100/Photo-Sphere-Viewer' }}
        with:
          name: cypress
          use-actions-summary: true
          path: cypress/reports/e2e.json
          reporter: mocha-json

  build-doc:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/workflows/shared/setup

      - name: build
        run: yarn ci:build-doc
