name: build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'examples/**'
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/workflows/shared/setup

      - name: build
        run: yarn ci:build

      - name: test summary
        uses: phoenix-actions/test-reporting@v15
        if: ${{ (success() || failure()) && github.repository == 'mistic100/Photo-Sphere-Viewer' }}
        with:
          name: build
          output-to: step-summary
          path: 'packages/*/reports/mocha.json'
          reporter: mocha-json

  e2e:
    if: ${{ !startsWith(github.ref_name, 'dependabot') }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/workflows/shared/setup

      - name: e2e
        run: |
          yarn ci:build
          yarn ci:e2e

      - name: test report
        uses: actions/upload-artifact@v4
        if: ${{ (success() || failure()) && github.repository == 'mistic100/Photo-Sphere-Viewer' }}
        with:
          name: e2e-report-${{ github.ref_name }}-${{ env.SHORT_SHA }}
          path: |
            cypress/reports/html
            !cypress/reports/html/.jsons

      - name: test summary
        uses: phoenix-actions/test-reporting@v15
        if: ${{ (success() || failure()) && github.repository == 'mistic100/Photo-Sphere-Viewer' }}
        with:
          name: e2e
          output-to: step-summary
          path: 'cypress/reports/html/.jsons/*.json'
          reporter: mochawesome-json

  build-doc:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            docs:
              - 'docs/**'
              - 'package.json'

      - if: steps.changes.outputs.docs == 'true'
        name: setup
        uses: ./.github/workflows/shared/setup

      - if: steps.changes.outputs.docs == 'true'
        name: build-doc
        run: yarn ci:build-doc
